### ISSUE TITLE
About the video_inpainting.

### ISSUE THREAD

**Issue by liuyifan6613** [zibojia/COCOCO#1]
Thanks for your wonderful work.
In the first step, when I download the video_inpainting ckpt, where can i get the video_inpainting pipeline?
![image](https://github.com/user-attachments/assets/84431e7f-b0ec-4669-9e44-7e5a10378747)

**Comment by zibojia** [comment]
you should modify the inference code, and put the path to the torch.load function. Maybe I should modify my code and make it easy to use. Thanks for  your suggestion.

**Comment by zibojia** [comment]
You can check the update version. Thanks for your attention. More disscussions can send the email to me (1155203591 @ link.cuhk.edu.hk).

**Comment by liuyifan6613** [comment]
Thanks for your reply! I'll try it.
